{% set version = "1.1" %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-rapportools
  version: {{ version|replace("-", "_") }}

source:
  fn: rapportools_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/rapportools_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/rapportools/rapportools_{{ version }}.tar.gz
  sha256: b5fab34bed484d20bb6cf27028f3d9009c482b079298d31a344f84675b342863

build:
  noarch: generic
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - r-base
    - r-pander
    - r-plyr
    - r-reshape

  run:
    - r-base
    - r-pander
    - r-plyr
    - r-reshape

test:
  commands:
    - $R -e "library('rapportools')"  # [not win]
    - "\"%R%\" -e \"library('rapportools')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=rapportools
  license: AGPL-3.0-only
  summary: Helper functions that act as wrappers to more advanced statistical methods with the advantage of having sane defaults for quick reporting.
  license_family: AGPL

  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/AGPL-3
extra:
  recipe-maintainers:
    - conda-forge/r
