{% set version = "1.1" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-rapportools
  version: {{ version|replace("-", "_") }}

build:
  merge_build_host: True  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-mass
    - r-pander
    - r-plyr
    - r-reshape2
  run:
    - r-base
    - r-mass
    - r-pander
    - r-plyr
    - r-reshape2

test:
  commands:
    - $R -e "library('rapportools')"           # [not win]
    - "\"%R%\" -e \"library('rapportools')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=rapportools
  license: AGPL-3.0-only
  summary: Helper functions that act as wrappers to more advanced statistical methods with the advantage of having sane defaults for quick reporting.
  license_family: AGPL
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/AGPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
