travis:
  secure:
    BINSTAR_TOKEN: Svue7o/xXjuRfH7MZhZrHxRjeR6mXGFDDAQAa8JuTg2MdAEQA4mqxyccB59f+VRLk04g2wWqPFGhBD9+ZJhAawqX2uAzk/R9mQYe/BHnUglQtlbnYEe5ARSatZAwGjB6g+2NUTl0f793Y9GD76AFrSq3qMGxlLpcw65vnJZPVjStii5o5f0vUlUsRPItc/PSD+X7vRsWcflP5jGFaZMs0qqcDp5zkPV+vdDzTr2vA7gr25nTTYod5KNFge03gQhLEQfX+zYclA5JgTaKicK+zjuISJdXvX44jaThwlP6aE3ocqnVWVQGqIbBH6+k0OXPJmNtP4cexKfHKsXr7vy7fHHjP4Qb5x1Wx60DADMnlFQmO3t/YjGdsH1/uo+8UdBVJcCMB2ir85YqgUkqIA7N97NqQyrHq/cSopF9/RL9VeEs7lAG/q87OpMazSGgwJ91+V8rT+idstSUkQL6k6dEwF35cjRb0JuH4tTd8JCVkohrhcfipgIu5ImnCCJ3t86gdPK7fL6ALJ8USnj169Di862084gdHNC/YzpHXzZUQumlEnZMAtIUZrJYXRgxXm6NI73x2JVo+PZupc290nL+3RhlscHzs/Xk9j27KjnlEOU5ttlRsAkaDisjgI2OPjYT673ADSVTAq8HjV0CDlEkXzf9ME6imKjwl0Juqu13Kco=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
