appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: jcEqz5K6OGDpNniWLpoKE+lICoHzd8DZ3xA7nLxRyEre8uTURn/E9DSMZ2vi6Gv/XrrgSpucif+AkZgaD/oxRBPQMTXMlV/sLIiAglRLvXxBLQPZYo/8Dy1X6+4UeAImVMPMkK87ySPjymlciWqaie8Rlq+MTM8P/xNwR4SOUYeAWdYZZpdmVvbef4UJxFEB71vM3tZyIktwKnBv7+b8a4xm1NQe+DxkZSK57B7Inz/jJLliTzQ8J2/NwpYKcvyuAP71QiMycAfFymdL08DgtFzn7+gewKL7MLy0wOfJfjjC9cGzdiZCHR0t9e54rrZJ7H4smaqQ+CEwPi+FK39UYQc/sWI35D0bo6NEwXGWbERias9k1lNSiLJDYIYGQs1jHVxfB06yt0X0aPFc+u2VU/Df4xZq9cAKPpeSIoEmIjWwj/73ko0ODPIBTt1Z9OuSgLwn2Y9vaTEwGq7aPrbbxAbzaevFiPDsqlFffhDnSbhnwXfS/7TlQCPI/T9YG5wSEhd0x0QRFRlDf+sn+bVY7mVhoJJGctqaPfDAEx4WgvoeR2Jjv8LlqmKUgzjLzEZ+MObYIW6Vg3X0UKjHxJ4NRT7An4xjiXFDF/jI5F2HBk35wy4LLEJH1YHC7trITe6vJG06n+toj0YgmdLOVaRujPE75myi5oAng3JJ5U4laSQ=
conda_forge_output_validation: true
