travis:
  secure:
    BINSTAR_TOKEN: yITWARAUeoUEYHljh+b8QARjRZV0hpBU0kDArmC6Uolz2Vb0pHXpzhN0asr1DCQdqPYX8DEF2V372fE9umMJlfu97numVKysQFKXoClF1M0va/Cl2GtKXKaHppLKAE4Hhqyr95Rn0zv6bvbI/EtC/9zMrFoD1wZ07KyuJyXTgOIeGO4kvjj0Qtt9wvGQc986B3lD7A4pHCUiFFQQjJSD1hR79VWO7HFYH4Ned5VEo7zr1VEa89tkpGxK7y+ZALdZOi9x492mOsnVRxcqzx28IOOQ6rx/4n5ep9fn3VkwCYD5SVna2TVc+piw4plIX4fhFQxW6qXClN3url20AX/qyjJBr88krDExvcyRLxh0MRwYg2y26sPD8jx5ZM9gjKeDiU7ASBfwwjLnqvUUv4a7OIyK+wutG2LVMkJSS309ywGMxDngsSxfGVmkqraBMFt7+V+RsLkntaXdEL0d+MsekrJnRCxs7G2FY4byzVZtnPPC1gwi86ylxKwvC0UbZM0UTf4udRUo6nVfGNwVBKqAiOMKA8T4F4/1zSJfzBdwYU74Nb2DZLydNh9Ej/TgRKIc5OtBjfpMU88P8lDB4J8XZEDQ2nsPrzzS/lyr3j38yqiyZo1+Q8nvmXkdiZe1VApbvhJlKNcocYEtuR9UBEkq6nqmVSZONWTXJH/4hFFCq30=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
