travis:
  secure:
    BINSTAR_TOKEN: lQNLmEE4znI1CAoYPheQkDAKu32qVrjHHPBaiqtWOp67n87AYLzCTyjJrNoCSw+w/t93jTv6keInrE2x53qly0jUUE3l8s6ik6bUHXmBgZNBTP2tFEHPVGpf/jqbil8QC2iVmUeu2y4Cm4vCW6SP+x1sb0taOzMxqj3l02K/xIqHW+/S6KV+jbt1rzqYjTHqqMRW40JPUzpmy4PTOAMOZnrDeXsQdM35kiVgXAsWR8rYhSWVFeHbT7poUC294fhwyVl8YCUWXmZabQsBrOF70ca2dZd/fJow+S8tWEwsrICXBFNmVu28K4WnhCvWftEFMPbEMegwiZagPMKD4op4D7faUttrCEsM25dN+N3YkVIEdIRv4b+FMw760KLslv1/pSOdTP51CbjrEs5hieLWfjhxMnKN7ljkZ2xDRR+AaOhTzvDdJRiw4wZtCuGEojpq9wDTYCQDPmsbnY8u+CmbR2SQDQQbtgrYpugZYZAOsvXCwN+KT0RqV+u6Gp4cqv5zT0ML4a2PSgF4jhCMHTpYzWfHFXwpzljr8N6eq3vocVVc13BCwob+O9bXSE7eoK2Z/NLKUDitZdxxrF0tNHB4Is1ALvYzlvFP4jwm/3iHPNs/UrNvJZsekkSpJso4EcL7lKZqe1mS8+i0MKD6QJK7lAoNSj+6GPYSuIb4qrkAHnA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
